### PR TITLE
Temporarily disable monitor thread

### LINKED ISSUE #2510: Race condition in thread_pool::n_threads_in_team()
As seen in the following stacktrace:
```
(gdb) bt
#0  0x00007f81abd14776 in dt::thread_team::size (this=0x0) at src/core/parallel/thread_team.cc:45
#1  0x00007f81abd0d441 in dt::thread_pool::n_threads_in_team (this=0x15ff420) at src/core/parallel/thread_pool.cc:163
#2  0x00007f81abd0d4f5 in dt::num_threads_in_team () at src/core/parallel/thread_pool.cc:197
#3  0x00007f81abe1a866 in dt::progress::progress_manager::update_view (this=0x7f80fc004580) at src/core/progress/progress_manager.cc:84
#4  0x00007f81abd12ef1 in dt::monitor_thread::run (this=0x3525850) at src/core/parallel/monitor_thread.cc:129
#5  0x00007f81abd139f6 in std::__invoke_impl<void, void (dt::monitor_thread::*)(), dt::monitor_thread*> (
    __f=@0x31d6750: (void (dt::monitor_thread::*)(dt::monitor_thread * const)) 0x7f81abd12d56 <dt::monitor_thread::run()>, __t=@0x31d6748: 0x3525850) at /usr/include/c++/7/bits/invoke.h:73
#6  0x00007f81abd134b0 in std::__invoke<void (dt::monitor_thread::*)(), dt::monitor_thread*> (__fn=@0x31d6750: (void (dt::monitor_thread::*)(dt::monitor_thread * const)) 0x7f81abd12d56 <dt::monitor_thread::run()>)
    at /usr/include/c++/7/bits/invoke.h:95
#7  0x00007f81abd14439 in std::thread::_Invoker<std::tuple<void (dt::monitor_thread::*)(), dt::monitor_thread*> >::_M_invoke<0ul, 1ul> (this=0x31d6748) at /usr/include/c++/7/thread:234
#8  0x00007f81abd143da in std::thread::_Invoker<std::tuple<void (dt::monitor_thread::*)(), dt::monitor_thread*> >::operator() (this=0x31d6748) at /usr/include/c++/7/thread:243
#9  0x00007f81abd143aa in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (dt::monitor_thread::*)(), dt::monitor_thread*> > >::_M_run (this=0x31d6740) at /usr/include/c++/7/thread:186
#10 0x00007f81ab2266df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f81b14b56db in start_thread (arg=0x7f8155de5700) at pthread_create.c:463
#12 0x00007f81b17ee88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

_Originally posted by @arnocandel in https://github.com/h2oai/h2oai/issues/15954#issuecomment-650710433_

### PR DESCRIPTION
**Pull request by st-pasha**
- `monitor_thread` is disabled for now, in order to check whether it has any effect on datatable's stability;
- without the monitor thread, the race condition in #2510 should no longer occur;
- `python_mutex` is converted into an `std::recursive_mutex`, in order to avoid potential deadlocks on the main thread;

If extensive testing shows this approach to be more viable than the previous ones, we'll remove the monitor thread's code entirely. For now it is merely commented out.

Closes #2510

### CODE REVIEW

**Comment by pseudotensor** [comment]
Thanks @st-pasha .  Has potential to fix a few issues that were identified before as issue with having extra dt threads around, specifically monitor thread:

https://github.com/h2oai/h2oai/issues/14309#issuecomment-591018701
https://github.com/h2oai/h2oai/issues/14742
https://github.com/h2oai/h2oai/issues/14442

Do you think it might solve issues with exception handling, where perhaps an exception was due to dt but couldn't be handled due to locks on the threading like seen below:

https://github.com/h2oai/h2oai/issues/14542

Recall we thought exception handling would be fixed by no asserts in python build + your fixes, but it was still occurring.

First noticed something specifically wrong with monitor thread hanging 6 months ago:

https://h2oai.slack.com/archives/C3YSYF5FS/p1576637410114800?thread_ts=1576637410.114800

```
2019-12-17 23:32:15,100 C:   D:      M:        21902 INFO   : Thread 2 (Thread 0x7f1a77713700 (LWP 23872)):
2019-12-17 23:32:15,100 C:   D:      M:        21902 INFO   : #0  0x00007f1aad8d5965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
2019-12-17 23:32:15,100 C:   D:      M:        21902 INFO   : #1  0x00007f1a9554b82c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
2019-12-17 23:32:15,100 C:   D:      M:        21902 INFO   : #2  0x00007f1a93642545 in dt::monitor_thread::run (this=0x4408210) at 
```

File: src/core/parallel/thread_pool.cc [hunk 1]
```diff
@@ -170,8 +185,8 @@ thread_team* thread_pool::get_team_unchecked() noexcept {
 
 
 void thread_pool::enable_monitor(bool a) noexcept {
-  init_monitor_thread();
-  monitor->set_active(a);
+  // init_monitor_thread();
+  // monitor->set_active(a);
```
Comment (oleksiyskononenko) [inline src/core/parallel/thread_pool.cc:189]: May be just add `(void) a;`, so that no warning is produced here.

**Comment by st-pasha** [comment]
@pseudotensor Note: We already join all threads in the "before fork" handler (https://github.com/h2oai/datatable/blob/master/src/core/parallel/thread_pool.cc#L46-L57), so when a fork happens there are no datatable threads around, either sleeping or active. However, this mechanism of thread shut down was implemented only recently.

As for the issues that you linked -- it's hard to say whether this PR will fix any of those, since for most of them we couldn't really reproduce or figure out why they happen at all. Still, it is probably fair to say that if something is hard to reproduce then it probably relates to  multithreading and race conditions. So, there is a non-zero chance that with this PR all those problems will "one day disappear, like a miracle".
