### PR TITLE
Do not do rereading step in fread

### LINKED ISSUE #1446: Improve re-read behavior in fread
`fread` spends lots of time re-reading, as evidenced for example in the log output below. Most of those re-reads, however, are avoidable. In fact, the majority of them occurs fairly early in the read process, so we could have just switched to the new stype, and then re-read (or updated) the beginning of the vector.

<details><summary>fread logs</summary>

```
[7] Finalize the datatable                                                      
  =============================
  Read 188,255,751 rows x 1,632 columns from 833GB input in 178:40.738s
   =    0.001s ( 0%) memory-mapping input line
   +    0.030s ( 0%) detecting parse parameters
   +    0.011s ( 0%) detecting column types using 100 sample rows
   +    0.015s ( 0%) allocating [207,425,508 x 1,632] frame (4454787689.754TB) of which 188,255,751 (91%) rows used
   + 5000.314s (47%) reading data using 16 threads
   + 5720.353s (53%) Rereading 332 columns due to out-of-sample type exceptions
      = 2651.618s (25%) reading into row-major buffers
      + 4854.480s (45%) saving into the output frame
      + 3214.570s (30%) waiting
   +    0.015s ( 0%) creating the final Frame
  =============================
  Column 1573 (****) bumped from Unknown to Str32 due to <<"Y">> on row 110
  Column 1417 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 131
  Column 1419 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 131
  Column 1421 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 131
  Column 289 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 142
  Column 236 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 151
  Column 237 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 151
  Column 238 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 151
  Column 239 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 151
  Column 240 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 151
  Column 563 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 151
  Column 564 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 151
  Column 35 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 158
  Column 593 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 158
  Column 1456 (****) bumped from Bool8/numeric to Int32 due to <<102>> on row 178
  Column 191 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 182
  Column 205 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 184
  Column 213 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 193
  Column 214 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 193
  Column 215 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 193
  Column 216 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 193
  Column 581 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 193
  Column 582 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 193
  Column 656 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 193
  Column 657 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 193
  Column 207 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 194
  Column 221 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 198
  Column 222 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 198
  Column 245 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 198
  Column 246 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 198
  Column 585 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 198
  Column 660 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 198
  Column 93 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 199
  Column 369 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 199
  Column 47 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 205
  Column 200 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 205
  Column 210 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 205
  Column 323 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 205
  Column 505 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 205
  Column 669 (****) bumped from Bool8/numeric to Int32 due to <<10>> on row 205
  Column 1420 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 222
  Column 929 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 233
  Column 1408 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 233
  Column 399 (****) bumped from Bool8/numeric to Int32 due to <<594>> on row 256
  Column 617 (****) bumped from Bool8/numeric to Int32 due to <<594>> on row 256
  Column 567 (****) bumped from Bool8/numeric to Int32 due to <<13>> on row 291
  Column 569 (****) bumped from Bool8/numeric to Int32 due to <<13>> on row 291
  Column 49 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 197 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 228 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 234 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 252 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 258 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 272 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 274 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 276 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 278 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 325 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 584 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 587 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 588 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 637 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 638 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 659 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 307
  Column 997 (****...) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1028 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1029 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1030 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1031 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1032 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1058 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1340 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1341 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1342 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1343 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1344 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1370 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1471 (****) bumped from Unknown to Str32 due to <<"HE">> on row 307
  Column 1472 (****) bumped from Unknown to Str32 due to <<"Q7129001">> on row 307
  Column 1504 (****) bumped from Unknown to Str32 due to <<"CV">> on row 307
  Column 1505 (****) bumped from Unknown to Str32 due to <<"F1SRM001">> on row 307
  Column 1506 (****) bumped from Unknown to Str32 due to <<"CV">> on row 307
  Column 1507 (****) bumped from Unknown to Str32 due to <<"B427S002">> on row 307
  Column 1515 (****) bumped from Unknown to Str32 due to <<"M">> on row 307
  Column 1516 (****) bumped from Unknown to Str32 due to <<"M">> on row 307
  Column 1586 (****) bumped from Unknown to Str32 due to <<"N">> on row 307
  Column 1587 (****) bumped from Unknown to Bool8/numeric due to <<0>> on row 307
  Column 1595 (****) bumped from Unknown to Str32 due to <<"ECKERT">> on row 307
  Column 1596 (****) bumped from Unknown to Int32 due to <<61>> on row 307
  Column 1597 (****) bumped from Unknown to Int32 due to <<38>> on row 307
  Column 1598 (****) bumped from Unknown to Int32 due to <<4>> on row 307
  Column 1608 (****) bumped from Int32 to Float64 due to <<4.125>> on row 307
  Column 1614 (****...) bumped from Int32 to Float64 due to <<4.125>> on row 307
  Column 565 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 308
  Column 1513 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 308
  Column 211 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 314
  Column 212 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 314
  Column 235 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 314
  Column 579 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 314
  Column 580 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 314
  Column 1629 (****) bumped from Unknown to Float64 due to <<1.5000>> on row 315
  Column 1630 (****) bumped from Unknown to Float64 due to <<2.7388>> on row 315
  Column 292 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 353
  Column 1491 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 417
  Column 244 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 514
  Column 250 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 514
  Column 255 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 514
  Column 256 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 514
  Column 257 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 514
  Column 77 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 534
  Column 80 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 534
  Column 353 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 534
  Column 356 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 534
  Column 583 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 581
  Column 586 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 581
  Column 619 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 581
  Column 623 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 581
  Column 627 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 581
  Column 631 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 581
  Column 62 (****) bumped from Bool8/numeric to Int32 due to <<153044>> on row 662
  Column 338 (****) bumped from Bool8/numeric to Int32 due to <<153044>> on row 662
  Column 243 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 683
  Column 566 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 683
  Column 1448 (****) bumped from Unknown to Int32 due to <<28997>> on row 730
  Column 1449 (****) bumped from Unknown to Int32 due to <<29000>> on row 730
  Column 1454 (****) bumped from Unknown to Int32 due to <<200005>> on row 730
  Column 1458 (****) bumped from Unknown to Int32 due to <<102>> on row 730
  Column 1459 (****) bumped from Unknown to Int32 due to <<210>> on row 730
  Column 1467 (****) bumped from Unknown to Bool8/numeric due to <<0>> on row 730
  Column 1510 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 730
  Column 1554 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 730
  Column 251 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 742
  Column 74 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 794
  Column 350 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 794
  Column 807 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 795
  Column 217 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 218 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 219 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 220 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 223 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 224 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 225 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 226 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 227 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 241 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 242 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 797
  Column 247 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 248 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 249 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 797
  Column 808 (****) bumped from Bool8/numeric to Int32 due to <<2428>> on row 799
  Column 71 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 809
  Column 347 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 809
  Column 34 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 45 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 838
  Column 57 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 59 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 60 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 63 (****) bumped from Bool8/numeric to Int32 due to <<3405>> on row 838
  Column 310 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 321 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 838
  Column 333 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 335 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 336 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 339 (****) bumped from Bool8/numeric to Int32 due to <<3405>> on row 838
  Column 589 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 838
  Column 291 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 849
  Column 36 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 855
  Column 37 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 855
  Column 66 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 855
  Column 42 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 863
  Column 318 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 863
  Column 72 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 867
  Column 348 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 867
  Column 568 (****) bumped from Bool8/numeric to Int32 due to <<-1>> on row 926
  Column 570 (****) bumped from Bool8/numeric to Int32 due to <<-1>> on row 926
  Column 1508 (****) bumped from Unknown to Str32 due to <<"CV">> on row 948
  Column 1509 (****) bumped from Unknown to Str32 due to <<"B1ULY001">> on row 948
  Column 1517 (****) bumped from Unknown to Str32 due to <<"M">> on row 948
  Column 264 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 959
  Column 1429 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 959
  Column 1521 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 959
  Column 1540 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 959
  Column 1544 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 959
  Column 981 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 1018
  Column 1439 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1132
  Column 1536 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1132
  Column 233 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1135
  Column 1524 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1135
  Column 1547 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1135
  Column 1493 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1159
  Column 253 (****) bumped from Bool8/numeric to Int32 due to <<6>> on row 1253
  Column 254 (****) bumped from Bool8/numeric to Int32 due to <<6>> on row 1253
  Column 290 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1282
  Column 1522 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1541
  Column 1545 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1541
  Column 75 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1542
  Column 78 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1542
  Column 81 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1542
  Column 351 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1542
  Column 354 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1542
  Column 357 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 1542
  Column 231 (****) bumped from Bool8/numeric to Int32 due to <<10>> on row 1548
  Column 232 (****) bumped from Bool8/numeric to Int32 due to <<10>> on row 1548
  Column 199 (****) bumped from Bool8/numeric to Int32 due to <<6>> on row 1898
  Column 229 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 2144
  Column 230 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 2144
  Column 1447 (****) bumped from Unknown to Int32 due to <<98679>> on row 2733
  Column 1466 (****) bumped from Unknown to Int32 due to <<351>> on row 2733
  Column 193 (****) bumped from Bool8/numeric to Int32 due to <<5>> on row 2752
  Column 265 (****) bumped from Bool8/numeric to Int32 due to <<5>> on row 2752
  Column 266 (****) bumped from Bool8/numeric to Int32 due to <<5>> on row 2752
  Column 273 (****) bumped from Bool8/numeric to Int32 due to <<5>> on row 2752
  Column 622 (****) bumped from Bool8/numeric to Int32 due to <<5>> on row 2752
  Column 195 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 2834
  Column 1473 (****) bumped from Unknown to Str32 due to <<"HE">> on row 3470
  Column 1474 (****) bumped from Unknown to Str32 due to <<"B617C042">> on row 3470
  Column 770 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 3680
  Column 261 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 4044
  Column 267 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 4044
  Column 268 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 4044
  Column 271 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4044
  Column 275 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 4044
  Column 626 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 4044
  Column 259 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4060
  Column 263 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4060
  Column 270 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4060
  Column 618 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4060
  Column 48 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4064
  Column 324 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4064
  Column 311 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4067
  Column 79 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4068
  Column 355 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4068
  Column 73 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4069
  Column 76 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4069
  Column 349 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4069
  Column 352 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4069
  Column 260 (****) bumped from Bool8/numeric to Int32 due to <<4>> on row 4077
  Column 983 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1430 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1431 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1440 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1441 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1512 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1523 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 1538 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4091
  Column 262 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4303
  Column 269 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4303
  Column 277 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4303
  Column 630 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4303
  Column 880 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 4344
  Column 1450 (****) bumped from Unknown to Bool8/numeric due to <<0>> on row 5051
  Column 1451 (****) bumped from Unknown to Int32 due to <<37199>> on row 5051
  Column 1452 (****) bumped from Unknown to Int32 due to <<37000>> on row 5051
  Column 1455 (****) bumped from Unknown to Int32 due to <<200804>> on row 5051
  Column 1460 (****) bumped from Unknown to Bool8/numeric due to <<0>> on row 5051
  Column 1461 (****) bumped from Unknown to Int32 due to <<120>> on row 5051
  Column 1465 (****) bumped from Unknown to Int32 due to <<240>> on row 5051
  Column 1467 (****) bumped from Bool8/numeric to Int32 due to <<225>> on row 5051
  Column 1470 (****) bumped from Unknown to Bool8/numeric due to <<0>> on row 5051
  Column 1475 (****) bumped from Unknown to Str32 due to <<"HE">> on row 5051
  Column 1476 (****) bumped from Unknown to Str32 due to <<"B6613209">> on row 5051
  Column 1555 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 5051
  Column 58 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 65 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 67 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 312 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 313 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 334 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 341 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 343 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 6888
  Column 1432 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8389
  Column 1442 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8389
  Column 1539 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8389
  Column 1543 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8389
  Column 1541 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8415
  Column 1526 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8416
  Column 1531 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8416
  Column 1549 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8416
  Column 39 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8548
  Column 41 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8548
  Column 315 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8548
  Column 317 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 8548
  Column 1450 (****) bumped from Bool8/numeric to Int32 due to <<39041>> on row 8715
  Column 1469 (****) bumped from Unknown to Int32 due to <<187>> on row 8715
  Column 40 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10001
  Column 316 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10001
  Column 512 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10001
  Column 1533 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10001
  Column 1482 (****) bumped from Unknown to Int32 due to <<12000>> on row 10303
  Column 51 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10336
  Column 209 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10336
  Column 327 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10336
  Column 1537 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 10362
  Column 1460 (****) bumped from Bool8/numeric to Int32 due to <<28>> on row 11700
  Column 1485 (****) bumped from Unknown to Int32 due to <<125000>> on row 12424
  Column 1468 (****) bumped from Unknown to Int32 due to <<60>> on row 13033
  Column 1470 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 13033
  Column 44 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 15044
  Column 320 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 15044
  Column 54 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 15371
  Column 330 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 15371
  Column 1542 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 15572
  Column 1546 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 15572
  Column 1525 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 15581
  Column 1438 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 21944
  Column 1535 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 21944
  Column 1433 (****) bumped from Bool8/numeric to Int32 due to <<3>> on row 21990
  Column 64 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 22212
  Column 340 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 22212
  Column 43 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 26431
  Column 319 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 26431
  Column 1587 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 30519
  Column 1532 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 38271
  Column 1437 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 44225
  Column 1550 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 48090
  Column 1551 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 48090
  Column 52 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 49383
  Column 53 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 49383
  Column 328 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 49383
  Column 329 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 49383
  Column 1434 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 60829
  Column 1443 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 61201
  Column 1436 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 76694
  Column 1529 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 83356
  Column 1534 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 83356
  Column 1552 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 83356
  Column 61 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 91101
  Column 337 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 91101
  Column 342 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 112169
  Column 1527 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 125504
  Column 1435 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 138868
  Column 1528 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 173014
  Column 1479 (****) bumped from Unknown to Int32 due to <<150000>> on row 271389
  Column 55 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 530439
  Column 331 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 530439
  Column 1530 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 976348
  Column 1553 (****) bumped from Bool8/numeric to Int32 due to <<2>> on row 976348
  Column 2 (****) switched from Str32 to Str64 because its size exceeded 2GB
  Column 1563 (****) switched from Str32 to Str64 because its size exceeded 2GB
  Column 3 (****) switched from Str32 to Str64 because its size exceeded 2GB
  Column 1579 (****) switched from Str32 to Str64 because its size exceeded 2GB
```
</details>

The log also shows a bug in display of the amount of bytes allocated (4454787689.754TB ...)

### LINKED ISSUE #1843: Eliminate "Rereading" pass in fread?
Current design of fread's algorithm follows the following rough steps:
  1. In the preliminary stage, fread selects several chunks within the file and parses them detecting the types of all fields. Parsed data is then discarded.
  2. Given the detected types, fread enters the main "Reading" stage, scanning through the entire file and saving the data into an output Frame.
  3. If during stage (2) any column's type was found to be incorrect, that column is marked as "type-bumped". If at the end of stage (2) there are any type-bumped columns, the entire file needs to be re-scanned: fread goes into the "Rereading" stage.

This algorithm was designed based on the assumption that type-detection in stage 1 would be reliable, that stage (3) would occur only rarely, and consequently its impact would be minimal. In practice, however, we see that the "rereading" pass occurs way too often, essentially doubling the dataset parse time. Moreover, the larger the input file (especially when it's > 100GB), the more likely that it would have to be re-read, which means we are very likely to double the already quite long read time.

In addition to the obvious time cost of the re-reading pass, it affects us in more subtle ways too. In particular, it prevents us from designing a single-pass algorithm, which means `fread` cannot consume data from a stream. Instead, we have to dump the content of the stream into a temporary file, fread that file, and then delete it. These are all overheads that could have been avoided if we knew that the data needs to be read only once.

So, can the "re-reading" pass be eliminated? It can, but there are certain costs associated with such redesign.

Remember that the need to "re-read" a column appears whenever we encounter a value that cannot be understood within the current column's type. For example, if the column is integer `2, 7, 11, 0, ...`, and then out of a sudden we see a value `3.4` in it. Then we say "oh well, looks like we'll need to reread this entire column" (and in practice it means rereading the entire file). But we could have approached this differently. We could have said "let's convert all the values we've read so far into doubles, and continue reading this column as type double". In practice it's slightly more complicated because of multiple threads having to maintain a consistent view of what the column's type is; but this is doable.

Cases like this are "easy", in the sense that they involve conversions that are unambiguous. There are, however, certain cases when the conversions **are** ambiguous, in particular when converting values into strings. For example, consider column containing values `0, +0, -0, 000`. These would be detected as integers `0,0,0,0`, as they should. However, if we later find that the column has to be converted to string, then the problem arises: the integer values that we have will be converted into four strings "0": the information that those zeros originally all looked differently as strings is lost.

It is because of these uncertainties, the "rereading" pass was deemed absolute necessity. Without it, the important invariant could be violated: reading data with auto-detected types could produce different results than reading data with explicitly specified types (but same as were auto-detected).

So the question really is -- is this invariant truly important? Are we willing to sacrifice speed (by a factor of 2 or even more), and sometimes disk usage (by a factor of 2), in order to satisfy it? Or should this choice be deferred to the user?

### PR DESCRIPTION
**Pull request by st-pasha**
Since the very early days, the design of fread was such that if any "type-bumps" happen in the middle of a file, then the corresponding column(s) will be marked as "require re-reading", and then at the end we would re-parse the entire file using the new column type. This approach has obvious drawbacks:
- the amount of time necessary to read the file almost doubles (and type bumps happen more often than you'd think);
- the logic behind type-bumping is very error-prone;
- it is impossible to read a stream-like input, where the data cannot be arbitrarily rewound;

The new approach for handling type-bumping is the following:
- When a type-bump occurs while reading a chunk, we enter the ordered section and temporarily suspend execution of other threads;
- While all other threads are paused, we:
  - "archive" the column which was type-bumped;
  - update the global types array with the new column parse types;
- After that, the parallel execution resumes from the start of the type-bumped chunk;
- (the process above may occur multiple times with different columns or different chunks);
- In the end, when the final frame is constructed, the columns that were comprised of multiple chunks are rbound together with automatic type promotion.

Closes #1843
Closes #1446

### CODE REVIEW

File: src/core/parallel/parallel_for_ordered.cc [hunk 1]
```diff
@@ -137,14 +140,23 @@ void OrderedTask::start_iteration(size_t i) {
...
-// inherited from the parent class is completely ignored.
-class WaitTask : public OrderedTask {
+// This subclass of `OrderedTask` is specifically used for waiting.
+// The state inherited from the parent class is completely ignored.
+//
+// Even though this class is used for waiting, it does not do any
+// waiting explicitly. Instead it finishes almost immediately and
+// then the thread tries to re-acquire a new task.
+//
+// After this task is executed, the parent OrderedJob will call
```
Comment (oleksiyskononenko) [inline src/core/parallel/parallel_for_ordered.cc:153]: back-ticks around the `OrderedJob`?

File: src/core/read/output_column.cc [hunk 2]
```diff
@@ -19,6 +19,7 @@
 // FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 // IN THE SOFTWARE.
 //------------------------------------------------------------------------------
+#include <iostream>
```
Comment (oleksiyskononenko) [inline src/core/read/output_column.cc:22]: Seems like this include can be safely removed.

File: src/core/tests/test_parallel_for_ordered.cc [hunk 3]
```diff
@@ -0,0 +1,396 @@
+//------------------------------------------------------------------------------
+// Copyright 2019-2020 H2O.ai
```
Comment (oleksiyskononenko) [inline src/core/tests/test_parallel_for_ordered.cc:2]: This seems to be a new file, so then may be `Copyright 2020`?

Comment (st-pasha) [reply src/core/tests/test_parallel_for_ordered.cc:2]: one of the tests here existed in `ztest_parallel_for.cc`, which was split into several files (https://github.com/h2oai/datatable/pull/2557/files#diff-e59505a7fb028ead863ca29e3394e6f6)

File: src/core/read/output_column.cc (hunk 2 above)
Comment (st-pasha) [reply src/core/read/output_column.cc:22]: yep

File: src/core/csv/reader_parsers.h [hunk 4]
```diff
@@ -184,6 +208,7 @@ class ParserIterator {
     value_type operator*() const;
 };
 
+// unused?
```
[the remark this answers is not in the document]
Comment (st-pasha) [reply src/core/csv/reader_parsers.h:211]: Yes, we need to do more cleanup around the ParserLibrary in general, but it's better to defer to a future PR.

File: ci/ext.py [hunk 5]
```diff
@@ -342,6 +342,7 @@ def build_extension(cmd, verbosity=3):
                 "-Wno-switch-enum",
                 "-Wno-weak-template-vtables",
                 "-Wno-weak-vtables",
+                "-Wno-implicit-int-float-conversion"
```
[the remark this answers is not in the document]
Comment (st-pasha) [reply ci/ext.py:345]: Oh, this sucks... I guess we'd have to remove this option and fix all the warnings the hard way...
