### PR TITLE
Fix writing large columns to file

### LINKED ISSUE #1387: Cannot save big Frame
If a Frame contains any column over 2GB in size, the frame will fail to save. This appears to be caused by the limitations of standard library's `write()`, which is unable to write more than 2GB of data.
```
import datatable as dt
frame0 = dt.Frame(A=[1.0, 2.0, 10.0])
frame0.nrows = 2**28  # 8 bytes per row
frame0.save("test.jay", format="jay")
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pasha/py36/lib/python3.6/site-packages/typesentry/config.py", line 155, in fdecorated
    ret = f(*args, **kws)
  File "/Users/pasha/github/datatable/datatable/nff.py", line 48, in save
    self.internal.save_jay(dest, self.names, _strategy)
RuntimeError: Cannot write to file: [errno 22] Invalid argument (bytes already written: 8)
```

### PR DESCRIPTION
**Pull request by st-pasha**
When a large column is written to file (> 2 GB), it will no longer fail with errno 22. Instead, we will write the data in chunks of 1GB until all data is written.

Closes #1387

### CODE REVIEW

File: c/writebuf.cc [hunk 1]
```diff
@@ -76,25 +76,43 @@ FileWritableBuffer::~FileWritableBuffer() {
 }
 
 
-size_t FileWritableBuffer::prep_write(size_t size, const void* src) {
+size_t FileWritableBuffer::prep_write(size_t src_size, const void* src)
```
Comment (oleksiyskononenko) [inline c/writebuf.cc]: Any way to parallelize this function? Or it is fast enough?

Comment (st-pasha) [reply c/writebuf.cc]: Yes, it's implemented in class `MmapWritableBuffer`. However, it does not always work inside docker instances.
