### PR TITLE
Make empty sort API consistent

### LINKED ISSUE #2220: Unexpected behavior when using empty sort()
When sort() is used in the by() position. Given a table like:
```
   | C0  C1
-- + --  --
 0 |  1   6
 1 |  1   5
 2 |  0   4
 3 |  0   3
 4 |  2   1
 5 |  2   2
```
If we use `DT.sort()` we get: 
```
   | C0  C1
-- + --  --
 0 |  0   3
 1 |  0   4
 2 |  1   5
 3 |  1   6
 4 |  2   1
 5 |  2   2
```
The default behavior is to sort by both columns. However, if we use `DT[:,:,sort()]` it is treated as an empty group by (it returns the same Frame). This isn't really a bug, but it seems inconsistent. `DT[:,:,sort(0)]` has the same behavior as `DT.sort(0)`, so it would make sense for `DT[:,:,sort()]` to have the same behavior as `DT.sort()`.

### PR DESCRIPTION
**Pull request by pradkrish**
Closes #2220

### CODE REVIEW

File: src/core/sort.cc [hunk 1]
```diff
@@ -1469,10 +1469,8 @@ py::oobj py::Frame::sort(const PKArgs& args) {
   dt::expr::EvalContext ctx(dt);
 
   if (args.num_vararg_args() == 0) {
-    py::otuple all_cols(dt->ncols());
-    for (size_t i = 0; i < dt->ncols(); ++i) {
-      all_cols.set(i, py::oint(i));
-    }
+    size_t n_cols = 0;
+    py::otuple all_cols(n_cols);
```
Comment (oleksiyskononenko) [inline src/core/sort.cc:1473]: I guess now a better name for this variable is `no_cols`, so you can just do `py::otuple no_cols(0);` here.

**Review by oleksiyskononenko — APPROVED** [review]

**Comment by oleksiyskononenko** [comment]
@pradkrish It looks great, thanks for the PR!

File: src/core/sort.cc (hunk 1 above)
Comment (pradkrish) [reply src/core/sort.cc:1473]: Done

File: docs/releases/v0.11.0.rst [hunk 2]
```diff
@@ -157,6 +157,8 @@
     previously it could return a dict of Frames if multiple sources were
     detected. Use :func:`iread()` if you need to read multi-source input.
 
+  -[api] Function: The behaviour of DT.sort() is made consistent with
+    DT[:, :, sort()] when the list of columns to sort is empty.
```
Comment (oleksiyskononenko) [inline docs/releases/v0.11.0.rst:161]: Guess it is better to say

```
The behaviour of  :meth:`.sort()`  is made consistent with the :func:`sort()` clause. When the list of columns to sort is empty, both will not sort any columns.
```

Note the usage of the `:meth` and `func:`, this will automatically create links to documentation.

File: docs/releases/v0.11.0.rst [hunk 3]
```diff
@@ -253,3 +255,4 @@
     1   @mmalohlava
     1   @Viktor-Demin
     1   @chrinide            <Chrinide>
+    1   @pradkrish           <Pradeep Krishnamurthy>
```
Comment (oleksiyskononenko) [inline docs/releases/v0.11.0.rst:258]: No need to worry about this, we have a tool that will automatically extract all the contribution details from github. Once released, this information will be included in this changelog.

File: docs/releases/v0.11.0.rst (hunk 2 above)
Comment (pradkrish) [reply docs/releases/v0.11.0.rst:161]: Thanks very much.

File: src/core/sort.cc [hunk 4]
```diff
@@ -1469,10 +1469,8 @@ py::oobj py::Frame::sort(const PKArgs& args) {
   dt::expr::EvalContext ctx(dt);
 
   if (args.num_vararg_args() == 0) {
-    py::otuple all_cols(dt->ncols());
-    for (size_t i = 0; i < dt->ncols(); ++i) {
-      all_cols.set(i, py::oint(i));
-    }
+    size_t no_cols = 0;
+    py::otuple all_cols(no_cols);
```
Comment (oleksiyskononenko) [inline src/core/sort.cc:1473]: Was it by accident that `no_cols` changed back to `all_cols`?

Comment (pradkrish) [reply src/core/sort.cc:1473]: The previous commit with 
```python
py::otuple no_cols(0)
ctx.add_sortby(py::osort(no_cols))
```
failed during the test. I couldn't open to find out where the error was, the server failed to load the page after many attempts. Since some compilers could be very strict, I assumed `0` could have been interpreted as `int` and failed since `otuple(size_t n)` expects `size_t`. Changing it back to the way it is now worked.

Comment (oleksiyskononenko) [reply src/core/sort.cc:1473]: I see, I don't think it would fail due to this reason, but you can even omit `0` and just say `py::otuple no_cols;`. By default the tuple will have zero columns.

Comment (pradkrish) [reply src/core/sort.cc]: well, I changed it back and it worked this time. :)

Comment (oleksiyskononenko) [reply src/core/sort.cc]: Yeah, no reason to work. Looks good, will merge now.

**Review by oleksiyskononenko — APPROVED** [review]
