### PR TITLE
Python framework, continued

### LINKED ISSUE #1220: Create new mechanism for translating Python to C++ code
Currently, in order to define Python-facing objects, we follow the standard Python methodology for defining an extension type (see eg https://docs.python.org/3/extending/newtypes.html). The problem with this approach are:
* This is idiomatic CPython, but not idiomatic C++. The code is hard to write and read.
* All methods have to be wrapped in macro-based wrappers that capture any C++ exceptions and translate them into Python code.
* Retrieving arguments/keyword arguments in methods is inefficient (it involves comparison of strings and format parameter scanning).
* Doesn't integrate well with `PyObj` objects.

The new system should aim to correct all these deficiencies. The expected API for defining an extension type is:
```C++
class Frame : public BasePyType<Frame> {
  DataTable* dt;

public:
  void m__init__(Args) override;
  void m__dealloc__() override;
  PyObj m__repr__() override;
  
  PyObj my_method1(Args);
  void my_method2(Args);
 
  static const char* classname() { return "datatable.Frame"; }
  static const char* classdoc() { return nullptr; }
  static void init_methods();
  static void init_getsetters();
};
```

This is a prerequisite for #1066

### PR DESCRIPTION
**Pull request by st-pasha**
This PR introduces further improvements towards implementing the new Python-C++ framework. Although it is far from complete, I anticipate that further changes will be done on case-by-case need, and there won't be a point in time when we could definitely say "the framework is ready, now the issue can be closed".

Closes #1220

### CODE REVIEW

File: c/python/args.cc [hunk 1]
```diff
@@ -39,35 +63,114 @@ Arg Args::get(const char*) const { throw AssertionError(); }
...
+    has_varkwds(vkwds),
+    arg_names(_names)
+{
+  xassert(n_args == arg_names.size());
+  if (has_varargs) xassert(n_pos_kwd_args == 0);
+  bound_args.resize(n_args);
+  for (size_t i = 0; i < n_args; ++i) {
+    bound_args[i].init(i, this);
+  }
+}
```
Comment (oleksiyskononenko) [inline c/python/args.cc]: `n_kwdonly_args` and `has_varkwds` are not used for the moment, right?

Comment (st-pasha) [reply c/python/args.cc]: That's right, as the warning message will keep pestering you about:
```
c/python/args.h:73:18: warning: private field 'n_kwdonly_args' is not used [-Wunused-private-field]
    const size_t n_kwdonly_args;
                 ^
c/python/args.h:76:18: warning: private field 'has_varkwds' is not used [-Wunused-private-field]
    const bool   has_varkwds;
                 ^
2 warnings generated.
```
