### PR TITLE
Fix Frame rendering style in docs

### LINKED ISSUE #1426: Update Frame's style in documentation
Now that the style of Frame's HTML representation has been updated (#1419), it's necessary to update the style in the docs too, so that they match.

### PR DESCRIPTION
**Pull request by st-pasha**
- The styling of Frame display in docs is now the same as in Jupyter;
- Row numbers are now displayed comma-separated;
- Comma-separation is not applied to numbers in the range 1000-9999.

Closes #1426

### CODE REVIEW

File: c/frame/_repr_html_.cc [hunk 1]
```diff
@@ -178,18 +180,18 @@ class HtmlWidget {
 
 
     void render_table_footer() {
-      html << "  <div class='footer'>";
+      html << "  <div class='footer'>\n";
       render_frame_dimensions();
```
Comment (oleksiyskononenko) [inline c/frame/_repr_html_.cc]: What is the reason you use `\n`s here, and don't use them in `render_data_row()`? I guess they're only required for HTML code to look nice, when opened through "View Source" or something like that?

Comment (st-pasha) [reply c/frame/_repr_html_.cc]: Yes, from HTML standpoint the newlines don't matter. However, we put that html into the docs (see  docs/using-datatable.rst for example), and we'd like to have at least some amount of readability there.
