### PR TITLE
Do not segfault when pickling an empty FTRL model

### LINKED ISSUE #1597: FTRL pickling segfaults
```
from datatable.lib._datatable import Ftrl
import pickle
pickle.dumps(Ftrl())
```
Segmentation fault

### PR DESCRIPTION
**Pull request by oleksiyskononenko**
`Ftrl()` object has an empty model, feature importances and feature names fields. This is now properly checked during pickling/unpickling to prevent segfaults. Several relevant tests have also been added.

Closes #1597

### CODE REVIEW

File: c/extras/py_ftrl.cc [hunk 1]
```diff
@@ -1042,14 +1048,17 @@ void Ftrl::m__setstate__(const PKArgs& args) {
...
+    for (size_t i = 0; i < fi_tuple.size(); ++i) {
+      (*dtft)[i]->set_fi(fi_tuple[i].to_frame()->copy());
+    }
   }
 
   // Set feature names
-  feature_names = pickle[3].to_frame()->copy();
-
+  if (pickle[3].is_frame()) {
+    feature_names = pickle[3].to_frame()->copy();
```
Comment (oleksiyskononenko) [inline c/extras/py_ftrl.cc]: @st-pasha do I need to make a shallow copy of each frame I unpickle?
